# Generated by Django 2.1.7 on 2019-05-16 09:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_item', models.CharField(max_length=255)),
                ('num_of_items', models.FloatField(default=0)),
                ('picture', models.ImageField(upload_to='profile_pics')),
                ('date', models.DateField(default=datetime.date.today)),
                ('due_date', models.DateField(default=datetime.datetime(2019, 5, 23, 17, 15, 30, 472171))),
                ('description', models.CharField(max_length=500)),
                ('borrower', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('picture', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('available', models.FloatField(default=0)),
                ('picture', models.ImageField(upload_to='profile_pics')),
                ('description', models.CharField(max_length=500)),
                ('categories', models.ManyToManyField(to='Items.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Pending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_item', models.CharField(max_length=255)),
                ('num_of_items', models.FloatField(default=0)),
                ('picture', models.ImageField(upload_to='profile_pics')),
                ('date', models.DateField(default=datetime.date.today)),
                ('description', models.CharField(max_length=500)),
                ('cat_name', models.ManyToManyField(to='Items.Category')),
                ('user_borrow', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='borrow',
            name='cat_name',
            field=models.ManyToManyField(to='Items.Category'),
        ),
    ]
