# Generated by Django 2.1.7 on 2019-05-18 02:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0003_auto_20190516_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrow',
            name='cat_name',
        ),
        migrations.AddField(
            model_name='borrow',
            name='cat_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Items.Category'),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2019, 5, 25, 10, 51, 34, 254772)),
        ),
        migrations.RemoveField(
            model_name='pending',
            name='cat_name',
        ),
        migrations.AddField(
            model_name='pending',
            name='cat_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Items.Category'),
        ),
    ]
